[package]
name = "mods-updater"
authors = ["Lameur"]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Lameur/mods-updater"
include = [
    "src/**/**",
    "docs/*.md",
    "Cargo.toml",
    "Cargo.lock",
    "LICENSE*",
    "EULA.rtf",
    "README.md",
    "assets/*",
]
description = "A minecraft mods updater for server"
license = "GPL-3.0"
license-file = "LICENSE"

[package.metadata.wix]
upgrade-guid = "6AB227C3-8F8F-43B1-904F-00D8E4E77045"
path-guid = "5FE37E1A-7B70-459E-9FF2-AD905066DBB9"
license = true
eula = "EULA.rtf"

[dependencies]
config = "0.15.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.44", features = ["full"] }

[build-dependencies]
cross = "0.2"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "fat"
