# Type de service, peux être un fichier pour docker 'compose.yml', un fichier '.jar' ou un script de démarrage comme 'run.sh' ou 'run.bat'.
# Valeur possible : jar, script ou docker
type=jar

# Chemins au script, compose.y[a]ml/docker-compose.y[a]ml ou au fichier jar
path=./test/mohist.jar

# Argument optionnel a passer a un script ou un ficher jar
args=-Xms10G -Xmx30G -XX:+PerfDisableSharedMem
