#:schema https://github.com/jdx/mise/blob/main/schema/mise-task.json

[build]
alias = "b"
run = "cargo build --all-features"
#sources = ["Cargo.*", "src/**/*.rs"]
outputs = ["target/debug/mise"]

[snapshots]
description = "update test snapshots"
run = "cargo insta test --all-features --accept --unreferenced delete"

[test]
description = "run all tests"
alias = 't'
run = ["mise tasks run test:unit"]

["test:unit"]
description = "run unit tests"
run = "cargo test --all-features"
env = { CARGO_TERM_COLOR = "always", "RUST_TEST_THREADS" = "8" }

[install-dev]
run = "cargo install --path . --debug"

[pre-commit]
env = { PRE_COMMIT = 1 }
run = ["mise run lint"]

[lint]
description = "Lint and tidy the code"
run = ['precious lint --all', 'precious tidy --all', 'precious rustfmt', 'precious clippy']
hide = true
alias = 'l'
